# -*- coding: utf-8 -*-
"""project_Datasci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XDeTuF4xOOatGGh_25qVCJqHl6Ex8M23

# ส่วนที่ 1 : การวิเคราะห์ภูมิทัศน์งานวิจัยเชิงเปรียบเทียบ

ขั้นตอนที่ 1 : คัดเลือกเเละกรอกข้อมูล
-เลือกกลุ่มเป้าหมาย ทั้งหมด 8 เเห่ง เช่น มหาวิทยาลัยสงขลานครินทร์ , จุฬาลงกรณ์มหาวิทยาลัย , มหาวิทยาลัยมหิดล , มหาวิทยาลัยเชียงใหม่ , มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี , มหาวิทยาลัยขอนแก่น , มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ , มหาวิทยาลัยแม่ฟ้าหลวง
-ระบุเเละสกัดข้อมูล
"""

import json
import csv
from datetime import datetime

# ===== ตั้งค่า =====
input_file = 'arxiv-metadata-oai-snapshot.json'
output_file = 'filtered_arxiv_with_universities2.csv'
target_categories = ['cs.AI', 'cs.LG', 'cs.CV']  # หมวดเป้าหมาย
start_year, end_year = 2014, 2024

# มหาวิทยาลัยเป้าหมาย
target_universities = {
    'PSU': ['Prince of Songkla', 'PSU Thailand', 'Songkla Univ','Prince of Songkla University','PSU'],
    'CU': ['Chulalongkorn University', 'Chula University', 'Chula','CU'],
    'MU': ['Mahidol University', 'Mahidol U', 'Mahidol','MU'],
    'CMU': ['Chiang Mai University', 'CMU','Chiang Mai'],
    'KMUTT': ['King Mongkut\'s University of Technology Thonburi', 'KMUTT'],
    'KKU': ['KKU','Khon Kaen University','Khon Kaen'],
    'KMUTNB': ['KMUTNB','King Mongkut\'s University of Technology North Bangkok'],
    'MFU': ['MFU','Mae Fah Luang University','Mae Fah Luang']
}

def find_affiliated_university(authors_text):
    if not authors_text:
        return None
    text = str(authors_text).lower()
    for uni_code, uni_names in target_universities.items():
        for name in uni_names:
            if name.lower() in text:
                return uni_code
    return None

# ===== เขียน Header CSV =====
with open(output_file, 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['id', 'title', 'categories', 'update_date', 'abstract', 'authors', 'university_code'])

# ===== อ่านไฟล์แบบ Streaming =====
with open(input_file, 'r', encoding='utf-8') as f:
    count = saved = 0

    for line in f:
        count += 1
        try:
            record = json.loads(line)
        except json.JSONDecodeError:
            continue

        # --- 1️⃣ กรองหมวดหมู่ ---
        categories = record.get('categories', '')
        if not any(cat in categories for cat in target_categories):
            continue

        # --- 2️⃣ กรองปี ---
        date_str = record.get('update_date', '')
        try:
            year = datetime.strptime(date_str, '%Y-%m-%d').year
        except:
            continue
        if year < start_year or year > end_year:
            continue

        # --- 3️⃣ ตรวจสอบมหาวิทยาลัยใน authors ---
        authors_text = record.get('authors', '') or record.get('authors_parsed', '')
        uni_code = find_affiliated_university(authors_text)
        if not uni_code:
            continue  # ไม่มีมหาวิทยาลัยเป้าหมาย → ข้าม

        # --- 4️⃣ เขียนบรรทัดลง CSV ---
        authors_clean = str(record.get('authors', '')).replace('\n', ' ').strip()

        with open(output_file, 'a', newline='', encoding='utf-8') as csvfile:
            writer = csv.writer(csvfile)
            writer.writerow([
                record.get('id', ''),
                record.get('title', '').replace('\n', ' '),
                categories,
                date_str,
                record.get('abstract', '').replace('\n', ' '),
                authors_clean,
                uni_code
            ])
        saved += 1

        if count % 100000 == 0:
            print(f'อ่านแล้ว {count:,} บรรทัด | เก็บไว้ {saved:,} บทความ')

print(f'✅ เสร็จสิ้น! เก็บข้อมูล {saved:,} บทความจากมหาวิทยาลัยเป้าหมาย')
print(f'📄 ไฟล์ที่ได้: {output_file}')

# =============================
# 📊 EDA & Visualization for ArXiv Filtered Dataset
# =============================
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx
from itertools import combinations
from collections import Counter

# 📌 1) Load dataset
csv_path = 'filtered_arxiv_with_universities2.csv'   # เปลี่ยน path ให้ถูกต้อง
df = pd.read_csv(csv_path, dtype=str, low_memory=False)

# --- Cleaning & preparation ---
df['update_date'] = pd.to_datetime(df['update_date'], errors='coerce')
df['year'] = df['update_date'].dt.year
df['categories'] = df['categories'].fillna('')
df['authors'] = df['authors'].fillna('')

print("✅ Dataset loaded")
print("Records:", len(df))
print("Universities distribution:")
print(df['university_code'].value_counts())

"""ขั้นตอนที่ 2 : วิเคราะห์ข้อมูลเชิงสำรวจเปรียบเทียบ"""

-ปริมาณผลงาน: เปรียบเทียบจำนวนผลงานตีพิมพ์ในแต่ละปีของแต่ละมหาวิทยาลัย

# 📈 2) Publications per year per university
# =============================
pubs_per_year = df.groupby(['university_code', 'year']).size().unstack(fill_value=0)

plt.figure(figsize=(12, 6))
for uni in pubs_per_year.index:
    plt.plot(pubs_per_year.columns, pubs_per_year.loc[uni], marker='o', label=uni)
plt.xlabel('Year')
plt.ylabel('Number of publications')
plt.title('Publications per Year per University')
plt.legend()
plt.tight_layout()
plt.show()

"""-สาขาที่โดดเด่น: วิเคราะห์และแสดงภาพเปรียบเทียบหมวดหมู่งานวิจัย (Categories) ที่แต่ละมหาวิทยาลัยให้ความสำคัญ"""

# 🧠 3) Top Categories per University
# =============================
# แยก categories ออกเป็น list
def split_categories(cat_str):
    if not isinstance(cat_str, str):
        return []
    return [c.strip() for c in cat_str.split() if c.strip()]

df['cat_list'] = df['categories'].apply(split_categories)
df_exploded = df.explode('cat_list')

# เลือก Top 10 categories ทั้ง dataset
top_categories = (
    df_exploded['cat_list'].value_counts()
    .head(10)
    .index
    .tolist()
)

# นับจำนวนของแต่ละ category ต่อมหาวิทยาลัย
cats_by_uni = {}
for uni in df['university_code'].unique():
    subset = df_exploded[df_exploded['university_code'] == uni]
    cnt = Counter(subset['cat_list'])
    cats_by_uni[uni] = [cnt.get(c, 0) for c in top_categories]

# วาดกราฟแบบ grouped bar chart
plt.figure(figsize=(14, 6))
x = range(len(top_categories))
width = 0.1

for i, uni in enumerate(sorted(cats_by_uni.keys())):
    offsets = [xi + (i - len(cats_by_uni)/2)*width for xi in x]
    plt.bar(offsets, cats_by_uni[uni], width=width, label=uni)

plt.xticks(x, top_categories, rotation=45, ha='right')
plt.xlabel('Categories')
plt.ylabel('Number of publications')
plt.title('Top 10 Categories by University')
plt.legend()
plt.tight_layout()
plt.show()

"""เครือข่ายความร่วมมือ: วิเคราะห์เบื้องต้นเกี่ยวกับเครือข่ายผู้เขียนร่วม (Co-authorship) เพื่อดูรูปแบบความร่วมมือภายในและระหว่างสถาบัน"""

# 👥 4) Co-authorship Network (Author-level)
# =============================
from networkx.algorithms import community
import matplotlib.cm as cm

def split_authors(s):
    """Split authors string into list"""
    if not isinstance(s, str) or s.strip() == '':
        return []
    # split by common separators
    if ';' in s:
        return [a.strip() for a in s.split(';') if a.strip()]
    if ' and ' in s:
        return [a.strip() for a in s.split(' and ') if a.strip()]
    if ',' in s:
        return [a.strip() for a in s.split(',') if a.strip()]
    return [s.strip()]

G = nx.Graph()

for _, row in df.iterrows():
    authors = split_authors(row['authors'])
    authors = [a for a in authors if a != '']
    for a in authors:
        if not G.has_node(a):
            G.add_node(a)
    for a, b in combinations(authors, 2):
        if G.has_edge(a, b):
            G[a][b]['weight'] += 1
        else:
            G.add_edge(a, b, weight=1)

print(f"Total authors in graph: {len(G)}")

# วาดกราฟเฉพาะ top 30 nodes ที่มี degree สูงสุด
deg = dict(G.degree())
top_authors = sorted(deg, key=deg.get, reverse=True)[:30]
subG = G.subgraph(top_authors)

subG = G.subgraph(top_authors).copy()
communities = list(community.greedy_modularity_communities(subG))

# สร้าง mapping: node -> community index
community_map = {}
for i, comm in enumerate(communities):
    for node in comm:
        community_map[node] = i

colors = [community_map[node] for node in subG.nodes()]

plt.figure(figsize=(12, 10))
pos = nx.spring_layout(subG, seed=42)
nx.draw_networkx_nodes(subG, pos, node_color=colors, cmap=cm.tab20, node_size=150)
nx.draw_networkx_edges(subG, pos, alpha=0.4)
nx.draw_networkx_labels(subG, pos, font_size=8)

plt.title('Co-authorship Network (Top 30 authors)\nColored by collaboration communities')
plt.axis('off')
plt.tight_layout()
plt.show()

from networkx.algorithms import community
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import networkx as nx

# --- 1) เลือก Top 20 authors ---
deg = dict(G.degree())
top_authors = sorted(deg, key=deg.get, reverse=True)[:20]
subG = G.subgraph(top_authors).copy()

# --- 2) หา communities ---
communities = list(community.greedy_modularity_communities(subG))
community_map = {}
for i, comm in enumerate(communities):
    for node in comm:
        community_map[node] = i
colors = [community_map[node] for node in subG.nodes()]

# --- 3) Layout: ปรับ k ให้ node ห่างขึ้น ---
# ค่า k เริ่มต้นของ nx.spring_layout คือ 1/sqrt(n)
# ลองเพิ่มเป็น 0.5 - 1.5 เพื่อให้ node กระจายตัวมากขึ้น
pos = nx.spring_layout(subG, seed=42, k=0.7, iterations=100)

# --- 4) วาดกราฟ ---
plt.figure(figsize=(14, 10))
nx.draw_networkx_nodes(subG, pos, node_color=colors, cmap=cm.tab20, node_size=250, alpha=0.9)
nx.draw_networkx_edges(subG, pos, alpha=0.4)
nx.draw_networkx_labels(subG, pos, font_size=9)

plt.title('Co-authorship Network (Top 20 authors)\n Colored by collaboration communities')
plt.axis('off')
plt.tight_layout()
plt.show()

"""# ส่วนที่ 2 การสร้างแบบจำลองทำนายศักยภาพ

ขั้นตอนที่ 3: นิยาม "ผลกระทบ" เเละเตรียมข้อมูล
-สกัดข้อมูลเพิ่มจากข้อมูลเดิม
-กำหนดตัวแปรเป้าหมาย
"""

import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer

df = pd.read_csv('filtered_arxiv_with_universities.csv')

# 1. จำนวนผู้เขียน
df['num_authors'] = df['authors'].fillna('').apply(lambda x: len(x.split(',')))

# 2. ความยาวบทคัดย่อ
df['abstract_length'] = df['abstract'].fillna('').apply(lambda x: len(x.split()))

# 3. หมวดหมู่ (แยกเป็น list แล้ว one-hot)
df['categories_list'] = df['categories'].apply(lambda x: x.split())
mlb = MultiLabelBinarizer()
cat_df = pd.DataFrame(mlb.fit_transform(df['categories_list']), columns=mlb.classes_)
df = pd.concat([df, cat_df], axis=1)

# 4. ปี
df['year'] = pd.to_datetime(df['update_date']).dt.year

# 5. Target
# 1️⃣ เงื่อนไขปี 2020–2024 → ให้ค่าเริ่มต้น 1
# ✅ เริ่มจากเงื่อนไขปี 2020–2024
df['impact_label'] = ((df['year'] >= 2020) & (df['year'] <= 2024)).astype(int)

# ✅ หาคอลัมน์ทั้งหมดที่ขึ้นต้นด้วย 'cs.'
cs_columns = ['cs.AI', 'cs.LG', 'cs.CV']

# ✅ บวกคะแนนเพิ่มตามจำนวนสาขา cs. ที่มีค่า 1
df['impact_label'] += df[cs_columns].sum(axis=1)

df

"""บทความที่มีผลกระทบสูง คือบทความที่มี impact สูง วิธีการคือหากบทความอยู่ในช่วงปี 2020 ถึงปี 2024 ให้1 หากไม่อยู่ในช่วงปีนั้นให้ 0 เเละถ้าบทความนั้นอยู่ในสาขา cs.AI , cs.LG , cs.CV ให้สาขาอย่างละ 1 เพิ่มขึ้นหากมีเงื่อนไขเป็นไปตามข้อความข้างต้นในคอลัมน์ impact_label"""

ขั้นตอนที่ 4: สร้างเเบบจำลองพื้นฐาน (Baseline Model)
-Feature Engineering
-สร้างเเบบจำลอง

"""Step 1 — เตรียมข้อมูล"""

# ✅ กำหนด features และ target
target = 'impact_label'

# เลือก features ที่สำคัญ
text_features = ['title', 'abstract']
numeric_features = ['year', 'num_authors', 'abstract_length']
categorical_features = ['university_code']

# One-hot categories เช่น cs.AI, cs.LG, ...
category_cols = ['cs.AI', 'cs.LG', 'cs.CV']

X = df[text_features + numeric_features + categorical_features + category_cols]
y = df[target]

"""Step 2 — แบ่งชุด Train/Test"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

"""ขั้นตอนที่ 5: เพิ่มประสิทธิภาพด้วยข้อมูลจากข้อความ
-Feature Engineering

Step 3 — สร้าง Baseline Model (Logistic Regression)
"""

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# ✅ Preprocessor
preprocessor = ColumnTransformer(
    transformers=[
        ('title_tfidf', TfidfVectorizer(max_features=3000, stop_words='english'), 'title'),
        ('abstract_tfidf', TfidfVectorizer(max_features=5000, stop_words='english'), 'abstract'),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features),
        ('num', StandardScaler(), numeric_features + category_cols)
    ]
)

# ✅ Logistic Regression Baseline
model = Pipeline(steps=[
    ('preprocess', preprocessor),
    ('clf', LogisticRegression(max_iter=500))
])

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

"""Step 4 — ประเมินผล"""

from sklearn.metrics import roc_auc_score

# AUC (สำหรับ classification)
if len(y.unique()) == 2:  # เฉพาะ binary
    y_prob = model.predict_proba(X_test)[:, 1]
    print("ROC AUC:", roc_auc_score(y_test, y_prob))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix - Logistic Regression')
plt.show()

"""Step 5 — สร้างเเบบจำลอง LightGBM"""

!pip install lightgbm

import lightgbm as lgb

lgbm_model = Pipeline(steps=[
    ('preprocess', preprocessor),
    ('clf', lgb.LGBMClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=-1,
        random_state=42
    ))
])

lgbm_model.fit(X_train, y_train)
y_pred_lgbm = lgbm_model.predict(X_test)

print("LightGBM model performance:")
print(classification_report(y_test, y_pred_lgbm))